services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: userpsql
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app